apiVersion: v1
kind: Service
metadata:
  name: {{ include "substation.fullname" . }}-broker
  labels:
    app: substation-broker
    {{- include "substation.labels" . | nindent 4 }}
spec:
  type: {{ .Values.broker.service.type }}
  ports:
    - port: {{ .Values.broker.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: substation-broker
