apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "substation.fullname" . }}-replica
  labels:
    app: substation-replica
    {{- include "substation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica.replicaCount }}
  serviceName: {{ include "substation.fullname" . }}-replicas
  selector:
    matchLabels:
      app: substation-replica
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app: substation-replica
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "substation.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/replica", "--config=/etc/replica.yaml"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts: 
            - name: www
              mountPath: /var/www
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.replica.resources | nindent 12 }}
      {{- with .Values.replica.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replica.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.replica.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: www  
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi

