apiVersion: v1
kind: Service
metadata:
  name: {{ include "substation.fullname" . }}-replica
  labels:
    app: substation-replica
    {{- include "substation.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.replica.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: substation-replica
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "substation.fullname" . }}-replicas
  labels:
    app: substation-replica
    {{- include "substation.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.replica.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: substation-replica

